version: "3.9"

services:

  app:
    build: .
    container_name: ticketflow-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build: .
    container_name: ticketflow-worker
    command: php artisan tickets:consume
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7-alpine
    container_name: ticketflow-redis
    ports:
      - "6379:6379"

networks:
  default:
    name: ticketflow-network